
import { useState } from 'react'
import Navbar from '../compos/Navbar'
import '../styles/globals.css'
import { SessionProvider } from 'next-auth/react'
import Head from 'next/head'
export default function App({ Component, pageProps: { session, ...pageProps } }) {
  const [yes, setYes] = useState(false)
  function toggleView() {
    setYes(!yes)
    var all = document.getElementsByTagName('*')
    if (!yes) {
      for (var i = 0, max = all.length; i < max; i++) {
        all[i].style.border = '1px solid rgba(255, 255, 255, 0.244)'
      }
    } else {
      for (var i = 0, max = all.length; i < max; i++) {
        all[i].style.border = 'none'
      }
    }
  }

  return (
    <SessionProvider session={session}>
      <Head>
        <title>Artverse | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="title" content="Artverse - The Ultimate Platform for Creatives" />
        <meta name="description" content="ARTVESE is an all-in-one platform for creatives to share projects, build portfolios, and connect with like-minded individuals. It also offers a unique parent link that consolidates users' social media accounts, making it easier to showcase their skills and engage with their online presence." />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="http://artverses.vercel.app/" />
        <meta property="og:title" content="Artverse - The Ultimate Platform for Creatives" />
        <meta property="og:description" content="ARTVESE is an all-in-one platform for creatives to share projects, build portfolios, and connect with like-minded individuals. It also offers a unique parent link that consolidates users' social media accounts, making it easier to showcase their skills and engage with their online presence." />
        <meta property="og:image" content="https://i.ibb.co/M8DJntr/image.png" />

        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="http://artverses.vercel.app/" />
        <meta property="twitter:title" content="Artverse - The Ultimate Platform for Creatives" />
        <meta property="twitter:description" content="ARTVESE is an all-in-one platform for creatives to share projects, build portfolios, and connect with like-minded individuals. It also offers a unique parent link that consolidates users' social media accounts, making it easier to showcase their skills and engage with their online presence." />
        <meta property="twitter:image" content="https://i.ibb.co/M8DJntr/image.png"></meta>
      </Head>
      <Navbar />
      <Component {...pageProps} />
      {/* <div className='debugCss' onClick={toggleView}>
        +
      </div> */}
    </SessionProvider>
  )
}
