import Head from 'next/head'
import Landing from '../compos/Homepage/NotLoggedIn/Landing'
import Platform from '../compos/Homepage/NotLoggedIn/Platform'
import Stats from '../compos/Homepage/NotLoggedIn/Stats'
import Footer from '../compos/Homepage/NotLoggedIn/Footer'
import Features from '../compos/Homepage/NotLoggedIn/Features'
import { useEffect, useState } from "react";
import { useSession } from 'next-auth/react'
import Dashboard from '../compos/Homepage/LoggedIn/Dashboard'


export default function Home() {
  var session = useSession()
  var [authenticated, setAuthenticated] = useState(false)
  var [loading, setLoading] = useState(true)
  useEffect(() => {
    if (session.status === 'authenticated') {
      setAuthenticated(true)
      setLoading(false)

    } else if (session.status === 'unauthenticated') {
      setAuthenticated(false)
      setLoading(false)
    }
  }, [session.status])

  return (
    <>
      <Head>
        <title>Artverse | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {(!authenticated && !loading) && <div>
        <Landing />
        <Platform />
        <Stats />
        <Features />
        <Footer />
      </div>}
      {(authenticated && !loading) && <div>
        <Dashboard />
      </div>}
      {loading && <div className='explore-load'>
        <img src="https://i.ibb.co/sWNd2Vc/ARTVERSE-1.gif" alt="loading" />

      </div>}



    </>
  )
}
