import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../compos/Navbar'
import Landing from '../compos/Homepage/Landing'
import Platform from '../compos/Homepage/Platform'
import Stats from '../compos/Homepage/Stats'
import Footer from '../compos/Homepage/Footer'
import Features from '../compos/Homepage/Features'
import { useInView } from "react-intersection-observer";
import { motion, useAnimation } from "framer-motion";
import { useEffect } from "react";


export default function Home() {
  return (
    <>
      <Head>
        <title>Artverse | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />

      <Platform />


      <Stats />


      <Features />

      <Footer />
    </>
  )
}
